### ISSUE TITLE
How to limit uploads a single file

### ISSUE THREAD

**Issue by prithvi16** [elninotech/uppload#15]
**Is your feature request related to a problem? Please describe.**
I checked configuration options there is no option to limit upload to a single file
**Describe the solution you'd like**
A config option that allows only single file upload.  

**Describe alternatives you've considered**
Also, a preview feature that loads previously uploaded image in the update form

**Additional context**
None

**Comment by AnandChowdhary** [comment]
Hi @prithvi16, thanks for opening an issue!

Since we built Uppload primarily for contexts like profile pictures, files, etc., Uppload currently only supports single-file uploads. This means that there is no configuration open for single files, because that's the only option presently available.

As per your idea for having a preview option to show the previously uploaded image, the `[data-uppload-value]` selector is used to automatically fill the upload value, and the `value` property of the Uppload configuration can be used to show the current value. You can try the demo on our website ([elninotech.github.io/uppload](https://elninotech.github.io/uppload/)) and see what I mean. The demo shows "Your profile picture" with the user's current image and lets her replace the picture with a new one, which is uploaded to Firebase.
