### ISSUE TITLE
Camera Access iOS 12.1

### ISSUE THREAD

**Issue by burkusmax** [elninotech/uppload#19]
**Describe the bug**
When trying to snap a picture from the camera it asks for access and I grant it. The box in uppload turns black and no image is displayed. Snapping a picture results in a black image.

**Expected behavior**
Camera access granted and be able to snap a picture with preview. 

**Smartphone**
 - Device: iPhone6 S
 - OS: [e.g. iOS 12.1
 - Browser: Safari

**Comment by AnandChowdhary** [comment]
Thanks for opening this issue, @burkusmax!

It seems to me like iOS Safari doesn't allow webcam access at all, or perhaps in very restricted conditions. I will have to do some more research, since all of the WebRTC/getUserMedia demos I tried to open on my phone (Chrome, iOS 12.1, iPhone XS) did not work.

I'll get back to you with some more research.

**Comment by thlassche** [comment]
@AnandChowdhary This one works on iPhone XS, iOS 12.1: https://webrtc.github.io/samples/src/content/getusermedia/gum/

**Comment by thlassche** [comment]
Support for iOS is added in 1.1.2
