### ISSUE TITLE
Multiple Uploaders

### ISSUE THREAD

**Issue by seritpt** [elninotech/uppload#28]
Is there any way to have multiples uploaders working on the same page?

I tried multiples combinations for that.

You can see here on https://jsfiddle.net/BUUdesign/eLak370c/1/

Thanks a lot :-)

**Comment by AnandChowdhary** [comment]
Hi @seritpt, instead of using the Uppload data attributes (which are useful when you have a single instance on a page), you can assign a class/other selector to the `call` and `bind` parameters. Then, you can create multiple instances of Uppload.

Here's the updated fiddle: https://jsfiddle.net/anandchowdhary/a54q0d2u/4/

**Comment by seritpt** [comment]
Wow. That's what I need. Thank you so much :-D
