### ISSUE TITLE
Uploading multiple files at once

### ISSUE THREAD

**Issue by Prince444** [elninotech/uppload#59]
is there any feature for uploading multiple images to one

like
[https://uploadcare.com/docs/file_uploads/widget/multi_upload/](https://uploadcare.com/docs/file_uploads/widget/multi_upload/)

**Comment by AnandChowdhary** [comment]
Thanks for opening this issue, @Prince444! Currently, multiple file uploads are not supported. However, in the upcoming release (December 2019), this will be supported.

**Comment by AnandChowdhary** [comment]
**Update:** Uppload is a great way to let users upload profile pictures and other images. It's an image-first uploading widget, not a general-purpose file uploader. This is further validated by support for image previews, cropping, (and new image editing features like filters coming in v2), which is why supporting uploading multiple files at once is not a priority and will not be shipped in v2.

Here's what I'm thinking: We can easily support multiple uploads using the local service (i.e., selecting multiple files from your computer), but it's going to be more complex to show previews for multiple files and even more complex to have image editing for multiple files and then sending them to the server.

Maybe we can come up with a compromise where multiple files can be supported, but image effects will not work. Maybe we can have a property for `multiple` and then directly upload the selected files instead of the middle step of image previews and editing. For people who want to use Uppload as a general-purpose file uploader, this should work.

```ts
const uppload = new Uppload({
  multiple: true
});
```

**Comment by AnandChowdhary** [comment]
I'll close this issue as soon as v2 is released.
