### ISSUE TITLE
Isolate Uppload

### ISSUE THREAD

**Issue by seritpt** [elninotech/uppload#66]
Is it possible to make it work on Jsfiddle? https://jsfiddle.net/SERIT/87t0ekzc/
I tried to download and the demo doens't work :-(

**Comment by seritpt** [comment]
It says on console "Uncaught SyntaxError: Cannot use import statement outside a module"

**Comment by AnandChowdhary** [comment]
Hi @seritpt, we have an example for JSFiddle on the [Examples](https://uppload.js.org/examples) page: https://jsfiddle.net/4yqc1dvm/3/.

**Comment by AnandChowdhary** [comment]
To reiterate, this is because you need a package manager (since Uppload has some dependencies that need to be bundled) and you cannot directly use `<script type="module">` if there are dependencies that need to be fetched from NPM first. I'm closing this issue as `wontfix` but will open it if we decide to create a "lean", dependency-free build in the future.
