### ISSUE TITLE
Add examples in this repo and fix CodeSandbox demos

### ISSUE THREAD

**Issue by mdolon** [elninotech/uppload#79]
**Describe the bug**
The following demos on the [Examples page](https://uppload.js.org/examples) are not working:
- [All features](https://codesandbox.io/s/jovial-sky-dm7cm)
- [Search on Unsplash](https://codesandbox.io/s/infallible-chebyshev-npy28)
- [Import from Instagram](https://codesandbox.io/s/boring-murdock-sbp87)
- [Basic Image Editor](https://codesandbox.io/s/charming-germain-u98cz)
- [Advanced Image Editor](https://codesandbox.io/s/winter-night-tjj4b)
- [Upload to Firebase](https://codesandbox.io/s/uppload-firebase-3zd9b)

**Additional context**
It seems the errors are related to `UpploadEffect` and `UpploadService` being invoked somewhere without instantiating a new class first.

**Comment by AnandChowdhary** [comment]
Thanks for opening this issue, @mdolon! I'll make sure I fix these examples soon. I think all I need to do is update the Uppload version; these were made during the beta stages and are probably using an older package version.

I think I'll also have an `./examples` directory in this repo and have them served to CodeSandbox from there, instead of directly hosting them there.

**Comment by AnandChowdhary** [comment]
Quick update: I've started to work in the new examples monorepo: [elninotech/uppload-examples](https://github.com/elninotech/uppload-examples)
